name: AWS SSM Get Parameters
description:
  Retrieve parameters from AWS SSM and export as environment variables

branding:
  icon: download
  color: orange

inputs:
  aws-region:
    description: The AWS region for the SSM client
    required: true
  parameter-pairs:
    required: true
    description: 'Comma-separated pairs in the format /ssm/path=ENV_VAR_NAME'
  with-decryption:
    required: false
    default: 'true'
    description: Whether to decrypt SecureString parameters

runs:
  using: node24
  main: ../dist/get-parameters/index.js
